stages:
  - build
  - push-docker-image

maven-build:
  image: maven:latest
  stage: build
  script:
    - mvn clean install
  artifacts:
    paths:
      - target

docker:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  stage: push-docker-image
  script:
    - echo $(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)') | tee version.txt
    - TAG=$(head -n 1 version.txt)
    - docker build -t gitlab-pipeline-dashboard:$TAG .
    - docker tag gitlab-pipeline-dashboard:$TAG jpiccaluga/gitlab-pipeline-dashboard:$TAG
    - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
    - docker push jpiccaluga/gitlab-pipeline-dashboard:$TAG
  only:
    - master