gitlab:
  pollingMs: 20000
  hostUrl: "https://gitlab.com/api/v4"
  accessToken: "J9g53Qt2sigRzCjj_Ewk"
  branchRefs:
    - label: 'master'
      regex: 'master'
    - label: 'feature/*'
      regex: '^feature\/\S*'
    - label: 'release/*'
      regex: 'release\/\S*'
  projects:
    - pathWithNamespace: "julien.piccaluga/gitlab-pipeline-dashboard-it"
# Optionally you can override global branchRefs at project level
#      branchRefs:
#        - 'master'
#        - '^feature\/\S*'
#        - '^release\/\S*'
server:
  port: 8080

management:
  endpoint:
    prometheus:
      cache:
        time-to-live: 0ms
      enabled: true

  endpoints:
    web:
      exposure:
        include: info, health, prometheus